# Generated by Django 2.2.5 on 2019-09-12 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mathobsession', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='likes',
        ),
    ]
