# Generated by Django 2.2.5 on 2019-09-10 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathobsession', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=30)),
                ('content', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=30)),
            ],
        ),
    ]
