# Generated by Django 2.2.5 on 2019-09-11 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathobsession', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='content',
            field=models.TextField(),
        ),
    ]
