# Generated by Django 2.2.5 on 2019-09-04 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathobsession', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='exercise',
            name='subject',
            field=models.ManyToManyField(blank=True, related_name='exercies', to='mathobsession.Subject'),
        ),
    ]
