<<<<<<< HEAD
# Generated by Django 2.2.5 on 2019-09-12 09:12
=======
# Generated by Django 2.2.5 on 2019-09-12 09:11
>>>>>>> bcd3a26d4bf454ac1b640b69bd35fe7338e7db89

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mathobsession', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='likes',
        ),
    ]
