# Generated by Django 2.2.5 on 2019-09-04 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathobsession', '0002_auto_20190904_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=25),
        ),
    ]
