# Generated by Django 2.2.5 on 2019-09-05 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathobsession', '0004_auto_20190904_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sketch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='exercise',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='exercises', to='mathobsession.Subject'),
        ),
    ]
