# Generated by Django 2.2.5 on 2019-09-05 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mathobsession', '0005_auto_20190905_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='sketches',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exericises', to='mathobsession.Sketch'),
        ),
    ]
