# Generated by Django 2.2.5 on 2019-09-05 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathobsession', '0007_auto_20190905_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='subjects',
            field=models.ManyToManyField(related_name='exercises', to='mathobsession.Subject'),
        ),
    ]
