# Generated by Django 2.2.5 on 2019-09-09 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathobsession', '0008_auto_20190905_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='icon',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='subject',
            name='image',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
